import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Layout_1 from "./components/layout/Layout_1";
import Layout_2 from "./components/layout/Layout_2";
import React, { useEffect, useRef, useState } from "react";
import useLocomotiveScroll from "./components/hooks/useLocomotiveScroll";


const Home: NextPage = () => {

  const ref = useRef(null);
  const [locomotiveScroll] = useLocomotiveScroll(ref)
  const [locomotiveStart, setLocomotiveStart] = useState(false);

  useEffect(() => {
    if (locomotiveStart&&locomotiveScroll!=undefined) {
      locomotiveScroll.current.update();
    }
  },[locomotiveStart])


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main data-scroll-container ref={ref} >
        {/* <Layout_1 /> */}
        <Layout_2 />
      </main>
    </>
  );
};

export default Home;
